// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesScssNamespace {
    export interface IStylesScss {
        profile_data__item_label: string;
        profile_data__item_value: string;
        profile_data_item: string;
        profile_default_photo: string;
        profile_photo: string;
    }
}

declare const StylesScssModule: StylesScssNamespace.IStylesScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StylesScssNamespace.IStylesScss;
};

export = StylesScssModule;
