// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesScssNamespace {
    export interface IStylesScss {
        files_upload__image: string;
        files_upload__image_list: string;
        files_upload__image_list_item: string;
        files_upload__image_place_holder: string;
        files_upload__input: string;
        files_upload__input_wrapper: string;
        files_upload__link_image: string;
        files_upload__link_image_list_item: string;
        files_upload__link_input_wrapper: string;
        files_upload__preview_image: string;
        files_upload__remove_image_button: string;
        files_upload__wrapper: string;
    }
}

declare const StylesScssModule: StylesScssNamespace.IStylesScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: StylesScssNamespace.IStylesScss;
};

export = StylesScssModule;
